#!/bin/sh
# Copyright 2010  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

N=100000

python -m timeit \
    -s 'import btree, random' \
    -s "n = $N" \
    -s 'array = range(n); random.shuffle(array)' \
    'btree.bsearch(array, 0)'

python -m timeit \
    -s 'import bisect, random' \
    -s "n = $N" \
    -s 'array = range(n); random.shuffle(array)' \
    'bisect.bisect(array, 0)'

