#!/usr/bin/python
# Copyright 2010, 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import cliapp
import logging
import sys
import ttystatus

import larch.fsck


class Fsck(cliapp.Application):

    def process_args(self, args):
        ts = ttystatus.TerminalStatus(period=0.1)
        ts.add(ttystatus.Literal('checking nodes '))
        ts.add(ttystatus.PercentDone('nodes_done', 'nodes_total', decimals=2))
        ts.add(ttystatus.Literal(' '))
        ts.add(ttystatus.RemainingTime('nodes_done', 'nodes_total'))
        ts.add(ttystatus.Literal(' remaining'))

        for dirname in args:
            forest = larch.open_forest(dirname=dirname)
            fsck = larch.fsck.Fsck(ts, forest)
            fsck.check_forest()
            

if __name__ == '__main__':
    Fsck().run()
